### ISSUE TITLE
Presentation markdown is invalid, may break in future.

### ISSUE THREAD

**Issue by gitpitch** [Drawaes/CodePersuit#1]
Just  a quick note to let you know that some of the markdown syntax being used in your GitPitch presentations for your tutorials is invalid and is likely to render incorrectly. It's simply the way you are using headings, Markdown expects a space to appear between the `#` and the text on that heading.

For example, you use:

```
##Let's Get Started!!
```

What you should be using is the following:

```
## Let's Get Started!!
``` 
This just an fyi, you should make this change to future-proof your presentations.

**Comment by Drawaes** [comment]
https://github.com/Drawaes/CodePersuit/commit/ad5f5504a9213461c8a86d53a6abba0158d6b92b
https://github.com/Drawaes/CodePersuit/commit/ddbcad817b932911597b448e109052d7aaaa4823
https://github.com/Drawaes/CodePersuit/commit/bc7cabe5134e381de57e93492ccdd785cddec819

Thanks, I have fixed all three presentations!

**Comment by Drawaes** [comment]
BTW gitpitch is cool 👍

**Comment by gitpitch** [comment]
That's great. And I'm very happy to hear you're enjoying using GitPitch. Whenever you have new presentations to share don't forget to Tweet and mention #gitpitch and I'll be happy to retweet to help you get the word out 👍
